import com.goldbookapp.model.*

data class ReceiptDetailModel(
        val data: Data?,
        val message: String?,
        val code: String?,
        val status: Boolean?,
        val errormessage: LoginModel.Errormessage?
) {

        data class Data(val transactionData: TransactionData?, val IRTData: List<SaleDetailModel.IRTData490504599>?)

        data class TransactionData(
                val id: Number?,
                val transaction_id: String?,
                val transaction_type_id: String?,
                val transaction_type_name: String?,
                val transaction_date: String?,
                val customer_code: String?,
                val display_name: String?,
                val contact_id: String?,
                val ledger_contact_type: String?,
                val vendor_bill_number: String?,
                val vendor_bill_date: String?,
                val is_gst_applicable: String?,
                val place_of_supply: String?,
                val party_po_no: String?,
                val tds_tcs_enable: String?,
                val reference: String?,
                val remarks: String?,
                val invoice_number: String?,
                val item: ArrayList<SaleDetailModel.Item1427117511>?,
                val total_net_wt_with_IRT: String?,
                val total_fine_wt_with_IRT: String?,
                val total_fine_wt_with_IRT_short_term: String?,
                val total_fine_wt_with_IRT_term: String?,
                val total_amount_with_IRT: String?,
                val total_quantity: String?,
                val total_gross_wt: String?,
                val total_less_wt: String?,
                val total_net_wt: String?,
                val total_fine_wt: String?,
                val total_misc_charges: String?,
                val total_silver_fine_wt_with_IRT: String?,
                val total_silver_fine_wt_with_IRT_short_term: String?,
                val total_silver_fine_wt_with_IRT_term: String?,
                val silver_total_quantity: String?,
                val silver_total_gross_wt: String?,
                val silver_total_less_wt: String?,
                val silver_total_net_wt: String?,
                val silver_total_fine_wt: String?,
                val silver_total_misc_charges: String?,
                val silver_total_amount: String?,
                val other_total_quantity: String?,
                val other_total_gross_wt: String?,
                val other_total_net_wt: String?,
                val other_total_misc_charges: String?,
                val other_total_amount: String?,
                val final_total_amount: String?,
                val tcs_tds_taxable_amount: String?,
                val tcs_amount: String?,
                val tcs_percentage: String?,
                val tds_amount: String?,
                val tds_percentage: String?,
                val sub_total: String?,
                val round_off_total: String?,
                val total_amount: String?,
                val grand_total: String?,
                val grand_total_short_term: String?,
                val grand_total_term: String?,
                val image: List<Images>?,
                val opening_cash_balance: String?,
                val opening_cash_balance_short_term: String?,
                val opening_cash_balance_term: String?,
                val running_cash_balance: String?,
                val running_cash_balance_short_term: String?,
                val running_cash_balance_term: String?,
                val closing_cash_balance: String?,
                val closing_cash_balance_short_term: String?,
                val closing_cash_balance_term: String?,
                val opening_fine_balance: String?,
                val opening_fine_balance_short_term: String?,
                val opening_fine_balance_term: String?,
                val opening_silver_fine_balance: String?,
                val opening_silver_fine_balance_short_term: String?,
                val opening_silver_fine_balance_term: String?,
                val running_fine_balance: String?,
                val running_fine_balance_short_term: String?,
                val running_fine_balance_term: String?,
                val closing_fine_balance: String?,
                val closing_fine_balance_short_term: String?,
                val closing_silver_fine_balance: String?,
                val closing_fine_balance_term: String?,
                val closing_silver_fine_balance_short_term: String?,
                val closing_silver_fine_balance_term: String?

        ){
                data class Images(val image_id: String?, val image: String?)
        }


}

